FROM openjdk:17-jdk-alpine

MAINTAINER rojberr <rojberr@outlook.com>

# Set user
USER spring:spring

# copy application .jar
ARG JAR_FILE=build/libs/mailsender-0.0.1-SNAPSHOT.jar
COPY ${JAR_FILE} app.jar

# expose port
EXPOSE 8080

# start app
ENTRYPOINT ["java","-jar","/app.jar"]