global:
  scrape_interval: 5s
scrape_configs:
  - job_name: 'mailsender-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:9000']
        labels:
          application: 'mailsender'